name: Build and Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2

    - uses: sksat/setup-rye@v0.25.0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build wheel
      run: rye build --wheel
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14

    # - name: Publish to PyPI
    #   uses: pypa/gh-action-pypi-publish@v1.4.2
    #   with:
    #     user: __token__  # Use the PyPI API token
    #     password: ${{ secrets.PYPI_API_TOKEN }}  # Set PYPI_API_TOKEN in your repository's secrets